MODEL_PARAMS = \
{ 'aggregationInfo': { 'days': 0,
                       'fields': [],
                       'hours': 0,
                       'microseconds': 0,
                       'milliseconds': 0,
                       'minutes': 0,
                       'months': 0,
                       'seconds': 0,
                       'weeks': 0,
                       'years': 0},
  'model': 'CLA',
  'modelParams': { 'anomalyParams': { u'anomalyCacheRecords': None,
                                      u'autoDetectThreshold': None,
                                      u'autoDetectWaitRecords': None},
                   'clParams': { 'alpha': 0.050050000000000004,
                                 'clVerbosity': 0,
                                 'regionName': 'CLAClassifierRegion',
                                 'steps': '1'},
                   'inferenceType': 'TemporalMultiStep',
                   'sensorParams': { 'encoders': { u'FlyHeight10': None,
                                                   u'FlyHeight11': None,
                                                   u'FlyHeight12': None,
                                                   u'FlyHeight5': None,
                                                   u'FlyHeight6': None,
                                                   u'FlyHeight7': None,
                                                   u'FlyHeight8': None,
                                                   u'FlyHeight9': None,
                                                   u'GList1': None,
                                                   u'GList2': None,
                                                   u'GList3': None,
                                                   u'PList': None,
                                                   u'ReadError1': None,
                                                   u'ReadError18': None,
                                                   u'ReadError19': None,
                                                   u'ReadError2': None,
                                                   u'ReadError20': None,
                                                   u'ReadError3': None,
                                                   u'Servo1': None,
                                                   u'Servo10': None,
                                                   u'Servo2': None,
                                                   u'Servo3': None,
                                                   u'Servo5': None,
                                                   u'Servo7': None,
                                                   u'Servo8': None,
                                                   '_classifierInput': { 'classifierOnly': True,
                                                                         'fieldname': 'class',
                                                                         'n': 121,
                                                                         'name': '_classifierInput',
                                                                         'type': 'SDRCategoryEncoder',
                                                                         'w': 21},
                                                   u'class': { 'fieldname': 'class',
                                                               'n': 121,
                                                               'name': 'class',
                                                               'type': 'SDRCategoryEncoder',
                                                               'w': 21}},
                                     'sensorAutoReset': None,
                                     'verbosity': 0},
                   'spEnable': True,
                   'spParams': { 'columnCount': 2048,
                                 'globalInhibition': 1,
                                 'inputWidth': 0,
                                 'maxBoost': 2.0,
                                 'numActiveColumnsPerInhArea': 40,
                                 'potentialPct': 0.8,
                                 'seed': 1956,
                                 'spVerbosity': 0,
                                 'spatialImp': 'cpp',
                                 'synPermActiveInc': 0.05,
                                 'synPermConnected': 0.1,
                                 'synPermInactiveDec': 0.05015},
                   'tpEnable': True,
                   'tpParams': { 'activationThreshold': 14,
                                 'cellsPerColumn': 32,
                                 'columnCount': 2048,
                                 'globalDecay': 0.0,
                                 'initialPerm': 0.21,
                                 'inputWidth': 2048,
                                 'maxAge': 0,
                                 'maxSegmentsPerCell': 128,
                                 'maxSynapsesPerSegment': 32,
                                 'minThreshold': 11,
                                 'newSynapseCount': 20,
                                 'outputType': 'normal',
                                 'pamLength': 3,
                                 'permanenceDec': 0.1,
                                 'permanenceInc': 0.1,
                                 'seed': 1960,
                                 'temporalImp': 'cpp',
                                 'verbosity': 0},
                   'trainSPNetOnlyIfRequested': False},
  'predictAheadTime': None,
  'version': 1}