MODEL_PARAMS = \
{ 'aggregationInfo': { 'days': 0,
                       'fields': [],
                       'hours': 0,
                       'microseconds': 0,
                       'milliseconds': 0,
                       'minutes': 0,
                       'months': 0,
                       'seconds': 0,
                       'weeks': 0,
                       'years': 0},
  'model': 'CLA',
  'modelParams': { 'anomalyParams': { u'anomalyCacheRecords': None,
                                      u'autoDetectThreshold': None,
                                      u'autoDetectWaitRecords': None},
                   'clParams': { 'alpha': 0.01962508905154251,
                                 'clVerbosity': 0,
                                 'regionName': 'CLAClassifierRegion',
                                 'steps': '1'},
                   'inferenceType': 'TemporalAnomaly',
                   'sensorParams': { 'encoders': { '_classifierInput': { 'classifierOnly': True,
                                                                         'clipInput': True,
                                                                         'fieldname': 'class',
                                                                         'maxval': 1,
                                                                         'minval': 0,
                                                                         'n': 115,
                                                                         'name': '_classifierInput',
                                                                         'type': 'ScalarEncoder',
                                                                         'w': 21},
                                                             u'class': { 'clipInput': True,
                                                                         'fieldname': 'class',
                                                                         'maxval': 1,
                                                                         'minval': 0,
                                                                         'n': 29,
                                                                         'name': 'class',
                                                                         'type': 'ScalarEncoder',
                                                                         'w': 21},
                                                             u'FlyHeight6': { 'clipInput': True,
                                                                         'fieldname': 'FlyHeight6',
                                                                         'maxval': 26728,
                                                                         'minval': 3019,
                                                                         'n': 29,
                                                                         'name': 'FlyHeight6',
                                                                         'type': 'ScalarEncoder',
                                                                         'w': 21
                                                             },
                                                             u'FlyHeight7': { 'clipInput': True,
                                                                         'fieldname': 'FlyHeight7',
                                                                         'maxval': 26728,
                                                                         'minval': 2577,
                                                                         'n': 29,
                                                                         'name': 'FlyHeight7',
                                                                         'type': 'ScalarEncoder',
                                                                         'w': 21
                                                             },
                                                             u'FlyHeight8': { 'clipInput': True,
                                                                         'fieldname': 'FlyHeight8',
                                                                         'maxval': 26728,
                                                                         'minval': 13748,
                                                                         'n': 29,
                                                                         'name': 'FlyHeight8',
                                                                         'type': 'ScalarEncoder',
                                                                         'w': 21
                                                             },
                                                             u'FlyHeight9': { 'clipInput': True,
                                                                         'fieldname': 'FlyHeight9',
                                                                         'maxval': 26728,
                                                                         'minval': 11168,
                                                                         'n': 29,
                                                                         'name': 'FlyHeight9',
                                                                         'type': 'ScalarEncoder',
                                                                         'w': 21
                                                             },
                                                             u'FlyHeight10': { 'clipInput': True,
                                                                         'fieldname': 'FlyHeight10',
                                                                         'maxval': 26728,
                                                                         'minval': 5667,
                                                                         'n': 29,
                                                                         'name': 'FlyHeight10',
                                                                         'type': 'ScalarEncoder',
                                                                         'w': 21
                                                             },
                                                             u'FlyHeight11': { 'clipInput': True,
                                                                         'fieldname': 'FlyHeight11',
                                                                         'maxval': 26728,
                                                                         'minval': 4540,
                                                                         'n': 29,
                                                                         'name': 'FlyHeight11',
                                                                         'type': 'ScalarEncoder',
                                                                         'w': 21
                                                             },
                                                             u'FlyHeight12': { 'clipInput': True,
                                                                         'fieldname': 'FlyHeight12',
                                                                         'maxval': 26728,
                                                                         'minval': 10610,
                                                                         'n': 29,
                                                                         'name': 'FlyHeight12',
                                                                         'type': 'ScalarEncoder',
                                                                         'w': 21
                                                             }},
                                     'sensorAutoReset': None,
                                     'verbosity': 0},
                   'spEnable': True,
                   'spParams': { 'columnCount': 2048,
                                 'globalInhibition': 1,
                                 'inputWidth': 0,
                                 'maxBoost': 2.0,
                                 'numActiveColumnsPerInhArea': 40,
                                 'potentialPct': 0.8,
                                 'seed': 1956,
                                 'spVerbosity': 0,
                                 'spatialImp': 'cpp',
                                 'synPermActiveInc': 0.05,
                                 'synPermConnected': 0.1,
                                 'synPermInactiveDec': 0.08568228006654939},
                   'tpEnable': True,
                   'tpParams': { 'activationThreshold': 12,
                                 'cellsPerColumn': 32,
                                 'columnCount': 2048,
                                 'globalDecay': 0.0,
                                 'initialPerm': 0.21,
                                 'inputWidth': 2048,
                                 'maxAge': 0,
                                 'maxSegmentsPerCell': 128,
                                 'maxSynapsesPerSegment': 32,
                                 'minThreshold': 10,
                                 'newSynapseCount': 20,
                                 'outputType': 'normal',
                                 'pamLength': 1,
                                 'permanenceDec': 0.1,
                                 'permanenceInc': 0.1,
                                 'seed': 1960,
                                 'temporalImp': 'cpp',
                                 'verbosity': 0},
                   'trainSPNetOnlyIfRequested': False},
  'predictAheadTime': None,
  'version': 1}